[tools]
aqua = "latest"
aws = "latest"
bun = "latest"
chezmoi = "latest"
deno = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
lua = "latest"
node = "lts"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
uv = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = []
